language: python
python:
    - "2.7"
    - "3.4"
before_install:
    - sudo apt-get install python-matplotlib
    - sudo apt-get install python-numpy
    - sudo apt-get install python-scipy
    - sudo apt-get install python-numexpr
    - sudo apt-get install python-imaging-tk
install:
    - pip install -r requirements.txt --use-mirrors
script:
    - py.test